### ISSUE TITLE
Steambridge creating invalid appmanifests

### ISSUE THREAD

**Issue by Tea23** [sirnuke/steambridge#6]
Upon running `steambridge install <anyappid>` the generated appmanifest file looks like the following:

```"AppState"
{
"	"AppID"	"410000"
	"Universe"	"1"
	"StateFlags"	"1026"
}
```

Spot the mistake? There is an extra " on line 3, before AppID.

Running this on Arch Linux.

**Comment by sirnuke** [comment]
Fixed per your merge request.
